// <auto-generated />
using System;
using MedMateAI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedMateAI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527034830_refacor latest data update")]
    partial class refacorlatestdataupdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedMateAI.Domain.Entities.AIAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AIAnalysisId");

                    b.Property<Guid?>("ConsultationSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisclaimerText")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.Property<Guid?>("RecoveryPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("text");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<Guid?>("SymptomAnalysisSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TestSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TreatmentJourneyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationSessionId");

                    b.HasIndex("RecoveryPlanId");

                    b.HasIndex("SymptomAnalysisSessionId");

                    b.HasIndex("TestSessionId");

                    b.HasIndex("TreatmentJourneyId");

                    b.HasIndex("UserId");

                    b.ToTable("AIAnalysis", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.AISystemConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ConfigId");

                    b.Property<Guid?>("ConsultationSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("RecoveryPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SymptomAnalysisSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("text");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("TestSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationSessionId");

                    b.HasIndex("RecoveryPlanId");

                    b.HasIndex("SymptomAnalysisSessionId");

                    b.HasIndex("TaskType")
                        .IsUnique();

                    b.HasIndex("TestSessionId");

                    b.ToTable("AISystemConfig", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.ConsultationQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("QuestionId");

                    b.Property<Guid>("ConsultationSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationSessionId");

                    b.ToTable("ConsultationQuestion", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.ConsultationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ConsultationSessionId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentSymptoms")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<Guid>("SymptomAnalysisSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VisitReason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("SymptomAnalysisSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("ConsultationSession", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.DepartmentRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("RecommendationId");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmergencySuggested")
                        .HasColumnType("boolean");

                    b.Property<int>("PriorityRank")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("SymptomAnalysisSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SymptomAnalysisSessionId");

                    b.ToTable("DepartmentRecommendation", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("DoctorId");

                    b.Property<string>("AcademicTitle")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("FacilityDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Specialty")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FacilityDepartmentId");

                    b.ToTable("Doctor", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.FacilityDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("FacilityDepartmentId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FacilityId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("FacilityDepartment", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.FeedbackReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("FeedbackId");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("UserId");

                    b.ToTable("FeedbackReview", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.FollowUpReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ReminderId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReminderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReminderType")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<Guid>("TreatmentLogId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentLogId");

                    b.HasIndex("UserId");

                    b.ToTable("FollowUpReminder", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("KnowledgeChunkId");

                    b.Property<string>("ChunkText")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmbeddingVectorReference")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KnowledgeDocumentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeDocumentId");

                    b.ToTable("KnowledgeChunk", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("KnowledgeDocumentId");

                    b.Property<string>("ContentUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KnowledgeSourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeSourceId");

                    b.ToTable("KnowledgeDocument", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.KnowledgeSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("KnowledgeSourceId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceName")
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .HasColumnType("text");

                    b.Property<int>("TrustLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeSource", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.LabIndicatorAdviceCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CacheId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoctorQuestions")
                        .HasColumnType("text");

                    b.Property<string>("FollowUpSuggestion")
                        .HasColumnType("text");

                    b.Property<Guid>("IndicatorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LifestyleAdvice")
                        .HasColumnType("text");

                    b.Property<string>("NutritionalAdvice")
                        .HasColumnType("text");

                    b.Property<string>("PossibleCauses")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrgencyLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WarningSigns")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IndicatorId", "Status")
                        .IsUnique();

                    b.ToTable("LabIndicatorAdviceCache", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.LabIndicatorMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("IndicatorId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("MaxReference")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinReference")
                        .HasColumnType("double precision");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("LabIndicatorMaster", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.LabTestResultDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ResultDetailId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IndicatorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TestSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("UserValue")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("IndicatorId");

                    b.HasIndex("TestSessionId");

                    b.ToTable("LabTestResultDetail", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.LabTestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TestSessionId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RawOcrText")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LabTestSession", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.MedicalDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("DepartmentId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MedicalDepartment", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.MedicalFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("FacilityId");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacilityName")
                        .HasColumnType("text");

                    b.Property<string>("FacilityType")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MedicalFacility", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("NotificationId");

                    b.Property<string>("Channel")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<Guid>("ReminderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReminderId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PatientProfileId");

                    b.Property<string>("AllergyNote")
                        .HasColumnType("text");

                    b.Property<string>("BloodType")
                        .HasColumnType("text");

                    b.Property<string>("ChronicDiseaseNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PatientProfile", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PaymentId");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserSubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSubscriptionId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PaymentTransactionId");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentProvider")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserSubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSubscriptionId");

                    b.ToTable("PaymentTransaction", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.RecoveryPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("RecoveryPlanId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PlanName")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("SymptomAnalysisSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TestSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TreatmentJourneyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SymptomAnalysisSessionId");

                    b.HasIndex("TestSessionId");

                    b.HasIndex("TreatmentJourneyId");

                    b.ToTable("RecoveryPlan", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.SessionSymptom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("SessionSymptomId");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SymptomAnalysisSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SymptomName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SymptomAnalysisSessionId");

                    b.ToTable("SessionSymptom", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PlanId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("integer");

                    b.Property<string>("FeatureLimitJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PlanName")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlan", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.SymptomAnalysisSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("SymptomAnalysisSessionId");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DisclaimerShown")
                        .HasColumnType("boolean");

                    b.Property<string>("InputText")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("SeverityLevel")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Processing");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SymptomAnalysisSession", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.TreatmentJourney", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TreatmentJourneyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DiagnosisSummary")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("UserId");

                    b.ToTable("TreatmentJourney", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.TreatmentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TreatmentLogId");

                    b.Property<string>("AiFeedbackNote")
                        .HasColumnType("text")
                        .HasColumnName("AI_FeedbackNote");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DailyTaskJson")
                        .HasColumnType("text");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMedicationTaken")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicationInstruction")
                        .HasColumnType("text");

                    b.Property<int?>("PainLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecoveryPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("SymptomNote")
                        .HasColumnType("text");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecoveryPlanId");

                    b.ToTable("TreatmentLog", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.UserMedication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UserMedicationId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DosageInstruction")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<Guid?>("TreatmentJourneyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentJourneyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMedication", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UserSubscriptionId");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscription", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFirstLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsProfileCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.AIAnalysis", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.ConsultationSession", "ConsultationSession")
                        .WithMany("AIAnalyses")
                        .HasForeignKey("ConsultationSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedMateAI.Domain.Entities.RecoveryPlan", "RecoveryPlan")
                        .WithMany("AIAnalyses")
                        .HasForeignKey("RecoveryPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedMateAI.Domain.Entities.SymptomAnalysisSession", "SymptomAnalysisSession")
                        .WithMany("AIAnalyses")
                        .HasForeignKey("SymptomAnalysisSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedMateAI.Domain.Entities.LabTestSession", "TestSession")
                        .WithMany("AIAnalyses")
                        .HasForeignKey("TestSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedMateAI.Domain.Entities.TreatmentJourney", "TreatmentJourney")
                        .WithMany("AIAnalyses")
                        .HasForeignKey("TreatmentJourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("AIAnalyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConsultationSession");

                    b.Navigation("RecoveryPlan");

                    b.Navigation("SymptomAnalysisSession");

                    b.Navigation("TestSession");

                    b.Navigation("TreatmentJourney");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.AISystemConfig", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.ConsultationSession", "ConsultationSession")
                        .WithMany("AISystemConfigs")
                        .HasForeignKey("ConsultationSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedMateAI.Domain.Entities.RecoveryPlan", "RecoveryPlan")
                        .WithMany("AISystemConfigs")
                        .HasForeignKey("RecoveryPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedMateAI.Domain.Entities.SymptomAnalysisSession", "SymptomAnalysisSession")
                        .WithMany("AISystemConfigs")
                        .HasForeignKey("SymptomAnalysisSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedMateAI.Domain.Entities.LabTestSession", "TestSession")
                        .WithMany("AISystemConfigs")
                        .HasForeignKey("TestSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConsultationSession");

                    b.Navigation("RecoveryPlan");

                    b.Navigation("SymptomAnalysisSession");

                    b.Navigation("TestSession");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.ConsultationQuestion", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.ConsultationSession", "ConsultationSession")
                        .WithMany("ConsultationQuestions")
                        .HasForeignKey("ConsultationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsultationSession");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.ConsultationSession", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.MedicalDepartment", "Department")
                        .WithMany("ConsultationSessions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMateAI.Domain.Entities.Doctor", "Doctor")
                        .WithMany("ConsultationSessions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedMateAI.Domain.Entities.MedicalFacility", "Facility")
                        .WithMany("ConsultationSessions")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMateAI.Domain.Entities.SymptomAnalysisSession", "SymptomAnalysisSession")
                        .WithMany("ConsultationSessions")
                        .HasForeignKey("SymptomAnalysisSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("ConsultationSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Doctor");

                    b.Navigation("Facility");

                    b.Navigation("SymptomAnalysisSession");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.DepartmentRecommendation", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.MedicalDepartment", "Department")
                        .WithMany("DepartmentRecommendations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMateAI.Domain.Entities.SymptomAnalysisSession", "SymptomAnalysisSession")
                        .WithMany("DepartmentRecommendations")
                        .HasForeignKey("SymptomAnalysisSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("SymptomAnalysisSession");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.FacilityDepartment", "FacilityDepartment")
                        .WithMany("Doctors")
                        .HasForeignKey("FacilityDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FacilityDepartment");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.FacilityDepartment", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.MedicalDepartment", "Department")
                        .WithMany("FacilityDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMateAI.Domain.Entities.MedicalFacility", "Facility")
                        .WithMany("FacilityDepartments")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.FeedbackReview", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.MedicalFacility", "Facility")
                        .WithMany("FeedbackReviews")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("FeedbackReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.FollowUpReminder", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.TreatmentLog", "TreatmentLog")
                        .WithMany("FollowUpReminders")
                        .HasForeignKey("TreatmentLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("FollowUpReminders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TreatmentLog");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.KnowledgeChunk", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.KnowledgeDocument", "KnowledgeDocument")
                        .WithMany("KnowledgeChunks")
                        .HasForeignKey("KnowledgeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeDocument");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.KnowledgeSource", "KnowledgeSource")
                        .WithMany("KnowledgeDocuments")
                        .HasForeignKey("KnowledgeSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeSource");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.LabIndicatorAdviceCache", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.LabIndicatorMaster", "Indicator")
                        .WithMany("LabIndicatorAdviceCaches")
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indicator");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.LabTestResultDetail", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.LabIndicatorMaster", "Indicator")
                        .WithMany("LabTestResultDetails")
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMateAI.Domain.Entities.LabTestSession", "TestSession")
                        .WithMany("LabTestResultDetails")
                        .HasForeignKey("TestSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indicator");

                    b.Navigation("TestSession");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.LabTestSession", b =>
                {
                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("LabTestSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.FollowUpReminder", "Reminder")
                        .WithMany("Notifications")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reminder");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.PatientProfile", b =>
                {
                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne("PatientProfile")
                        .HasForeignKey("MedMateAI.Domain.Entities.PatientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.Payment", b =>
                {
                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMateAI.Domain.Entities.UserSubscription", "UserSubscription")
                        .WithMany("Payments")
                        .HasForeignKey("UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMateAI.Domain.Entities.UserSubscription", "UserSubscription")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.RecoveryPlan", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.SymptomAnalysisSession", "SymptomAnalysisSession")
                        .WithMany("RecoveryPlans")
                        .HasForeignKey("SymptomAnalysisSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedMateAI.Domain.Entities.LabTestSession", "TestSession")
                        .WithMany("RecoveryPlans")
                        .HasForeignKey("TestSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedMateAI.Domain.Entities.TreatmentJourney", "TreatmentJourney")
                        .WithMany("RecoveryPlans")
                        .HasForeignKey("TreatmentJourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SymptomAnalysisSession");

                    b.Navigation("TestSession");

                    b.Navigation("TreatmentJourney");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.SessionSymptom", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.SymptomAnalysisSession", "SymptomAnalysisSession")
                        .WithMany("SessionSymptoms")
                        .HasForeignKey("SymptomAnalysisSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SymptomAnalysisSession");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.SymptomAnalysisSession", b =>
                {
                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("SymptomAnalysisSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.TreatmentJourney", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.MedicalDepartment", "Department")
                        .WithMany("TreatmentJourneys")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedMateAI.Domain.Entities.MedicalFacility", "Facility")
                        .WithMany("TreatmentJourneys")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("TreatmentJourneys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.TreatmentLog", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.RecoveryPlan", "RecoveryPlan")
                        .WithMany("TreatmentLogs")
                        .HasForeignKey("RecoveryPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecoveryPlan");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.UserMedication", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.TreatmentJourney", "TreatmentJourney")
                        .WithMany("UserMedications")
                        .HasForeignKey("TreatmentJourneyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("UserMedications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TreatmentJourney");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("MedMateAI.Domain.Entities.SubscriptionPlan", "Plan")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("MedMateAI.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MedMateAI.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.ConsultationSession", b =>
                {
                    b.Navigation("AIAnalyses");

                    b.Navigation("AISystemConfigs");

                    b.Navigation("ConsultationQuestions");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("ConsultationSessions");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.FacilityDepartment", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.FollowUpReminder", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.Navigation("KnowledgeChunks");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.KnowledgeSource", b =>
                {
                    b.Navigation("KnowledgeDocuments");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.LabIndicatorMaster", b =>
                {
                    b.Navigation("LabIndicatorAdviceCaches");

                    b.Navigation("LabTestResultDetails");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.LabTestSession", b =>
                {
                    b.Navigation("AIAnalyses");

                    b.Navigation("AISystemConfigs");

                    b.Navigation("LabTestResultDetails");

                    b.Navigation("RecoveryPlans");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.MedicalDepartment", b =>
                {
                    b.Navigation("ConsultationSessions");

                    b.Navigation("DepartmentRecommendations");

                    b.Navigation("FacilityDepartments");

                    b.Navigation("TreatmentJourneys");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.MedicalFacility", b =>
                {
                    b.Navigation("ConsultationSessions");

                    b.Navigation("FacilityDepartments");

                    b.Navigation("FeedbackReviews");

                    b.Navigation("TreatmentJourneys");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.RecoveryPlan", b =>
                {
                    b.Navigation("AIAnalyses");

                    b.Navigation("AISystemConfigs");

                    b.Navigation("TreatmentLogs");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.SymptomAnalysisSession", b =>
                {
                    b.Navigation("AIAnalyses");

                    b.Navigation("AISystemConfigs");

                    b.Navigation("ConsultationSessions");

                    b.Navigation("DepartmentRecommendations");

                    b.Navigation("RecoveryPlans");

                    b.Navigation("SessionSymptoms");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.TreatmentJourney", b =>
                {
                    b.Navigation("AIAnalyses");

                    b.Navigation("RecoveryPlans");

                    b.Navigation("UserMedications");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.TreatmentLog", b =>
                {
                    b.Navigation("FollowUpReminders");
                });

            modelBuilder.Entity("MedMateAI.Domain.Entities.UserSubscription", b =>
                {
                    b.Navigation("PaymentTransactions");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MedMateAI.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("AIAnalyses");

                    b.Navigation("ConsultationSessions");

                    b.Navigation("FeedbackReviews");

                    b.Navigation("FollowUpReminders");

                    b.Navigation("LabTestSessions");

                    b.Navigation("Notifications");

                    b.Navigation("PatientProfile");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("Payments");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SymptomAnalysisSessions");

                    b.Navigation("TreatmentJourneys");

                    b.Navigation("UserMedications");

                    b.Navigation("UserSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
