name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - devprovn

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore MedMateAI.sln

      - name: Build
        run: dotnet build MedMateAI.sln -c Release --no-restore
